# This is a basic workflow to help you get started with Actions

name: Deploy to Dev

# Controls when the workflow will run
on:

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  exportAdfArmTemplates:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    environment: dev
    
    steps:
    - name: Export ARM Template
      id: export
      uses: Azure/data-factory-export-action@v1.0.2
      with:
        path: ./src
