# This is a basic workflow to help you get started with Actions

name: Deploy to Dev

# Controls when the workflow will run
on:
  pull_request:
  
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  exportAdfArmTemplates:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    environment: test
    
    steps:
    - name: Check out repository code
      uses: actions/checkout@v2
        
    - name: Export ARM Template
      id: export
      uses: Azure/data-factory-export-action@v1.0.2
      with:
        path: ./src
        # id: '/subscriptions/c059c401-bbbb-4dac-be3c-12b3a41c77ee/resourceGroups/rg-ncds-dev/providers/Microsoft.DataFactory/factories/adf-ncds-dev'
        
    - name: Validate Data Factory resources
      uses: Azure/data-factory-validate-action@v1.1.5
      with:
         path: ./src [optional]
         
    - name: Login via Az module
      uses: azure/login@v1
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}
        enable-AzPSSession: true
        
        
    - name: Deploy resources
      uses: Azure/data-factory-deploy-action@v1.2.0
      with:
        resourceGroupName: rg-ncds-test
        dataFactoryName: adf-ncds-test
        armTemplateFile: '${{ steps.export.outputs.arm-template-directory }}/ARMTemplateForFactory.json'
        armTemplateParametersFile: '${{ steps.export.outputs.arm-template-directory }}/ARMTemplateParametersForFactory.json'
        additionalParameters: 'factoryName=adf-ncds-test ls_adls_properties_typeProperties_url=https://adlsvgtest.dfs.core.windows.net'

