# This is a basic workflow to help you get started with Actions

name: Deploy to Dev

# Controls when the workflow will run
on:

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  exportAdfArmTemplates:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    environment: dev
    
    steps:
    - name: Check out repository code
      uses: actions/checkout@v2
        
    - name: Export ARM Template
      id: export
      uses: Azure/data-factory-export-action@v1.0.2
      with:
        path: ./src
        # id: '/subscriptions/c059c401-bbbb-4dac-be3c-12b3a41c77ee/resourceGroups/rg-ncds-dev/providers/Microsoft.DataFactory/factories/adf-ncds-dev'
       
