# This is a basic workflow to help you get started with Actions

name: Build

# Controls when the workflow will run
on:
  push:
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  Validate and Export:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    environment: test
    
    steps:
    - name: Check out repository code
      uses: actions/checkout@v2
        
    - name: Validate Data Factory resources
      uses: Azure/data-factory-validate-action@v1.1.5
      with:
         path: ./src [optional]
      
    - name: Export ARM Template
      id: export
      uses: Azure/data-factory-export-action@v1.0.2
      with:
        path: ./src
