name: Pester TEST

# Controls when the workflow will run
on:

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  exportAdfArmTemplates:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    environment: test
    
    steps:
    - name: Check out repository code
      uses: actions/checkout@v2
    
    - name: Run Pester
      uses: azure/powershell@v1
      with:
        inlineScript: |
          Invoke-Pester -Script 'test/RunTests.ps1'
        azPSVersion: "latest"
